import type { CrawlResult, SummaryAsset } from '../types/index.js';

/**
 * Generate Obsidian-compatible Markdown with YAML frontmatter from crawl and summary data.
 */
export function buildObsidianNote(result: CrawlResult, summary: SummaryAsset): string {
  const { topic, source, crawledAt } = result;
  const {
    oneLineSummary,
    sections,
    keyConcepts,
    usagePatterns,
    codeExamples,
    gotchas,
    sourceUrls,
  } = summary;

  const lines: string[] = [];

  // --- YAML frontmatter ---
  lines.push('---');
  lines.push(`topic: ${topic}`);
  lines.push(`source: ${source}`);
  lines.push(`crawledAt: "${crawledAt}"`);
  lines.push(`tags: [docs, ${topic.toLowerCase().replace(/\s+/g, '-')}, testing, automation]`);
  lines.push('---');
  lines.push('');

  // --- Title ---
  lines.push(`# ${topic} - Documentation Asset`);
  lines.push('');

  // --- Overview ---
  lines.push('## Overview');
  lines.push('');
  lines.push(oneLineSummary);
  lines.push('');

  // --- Documentation Sections ---
  if (sections.length > 0) {
    lines.push('## Documentation Sections');
    lines.push('');
    for (const section of sections) {
      lines.push(`### ${section.type}`);
      for (const pageUrl of section.pages) {
        // Convert to Obsidian wiki-link style
        const wikiPath = pageUrl.replace(/^https?:\/\//, '');
        lines.push(`- Pages: [[${wikiPath}]]`);
      }
      if (section.keyHeadings.length > 0) {
        lines.push(`- Key Headings: ${section.keyHeadings.join(', ')}`);
      }
      lines.push('');
    }
  }

  // --- Key Concepts ---
  lines.push('## Key Concepts');
  lines.push('');
  for (const concept of keyConcepts) {
    lines.push(`- ${concept}`);
  }
  lines.push('');

  // --- Usage Patterns ---
  lines.push('## Usage Patterns');
  lines.push('');
  const patternsToShow = usagePatterns.slice(0, 10);
  patternsToShow.forEach((pattern, i) => {
    lines.push(`${i + 1}. ${pattern}`);
  });
  lines.push('');

  // --- Code Examples ---
  if (codeExamples.length > 0) {
    lines.push('## Code Examples');
    lines.push('');
    for (const example of codeExamples) {
      const lang = example.language ?? '';
      lines.push(`\`\`\`${lang}`);
      lines.push(example.code.trim());
      lines.push('```');
      lines.push('');
    }
  }

  // --- Gotchas & Notes ---
  if (gotchas.length > 0) {
    lines.push('## Gotchas & Notes');
    lines.push('');
    for (const gotcha of gotchas.slice(0, 10)) {
      lines.push(`- ${gotcha}`);
    }
    lines.push('');
  }

  // --- Sources ---
  lines.push('## Sources');
  lines.push('');
  for (const url of sourceUrls) {
    lines.push(`- [${url}](${url})`);
  }
  lines.push('');

  lines.push('---');
  lines.push('*Generated by docs-assetizer*');

  return lines.join('\n');
}
